experiment:
  name: train_simple_model
  overwrite: false
  batch_size: 32
  mode: train

data:
  base_dir: data
  spider_dataset_name: spider
  ambiqt_dataset_name: ambiQT

preprocessing:
  used_coref: false
  use_dependency: false
  opensearch: true

test:
  do_run_test: false
