experiment:
  name: all_experiments
  overwrite: false
  batch_size: 32
  mode: dev

data:
  base_dir: data
  spider_dataset_name: spider
  ambiqt_dataset_name: ambiQT
  bird_dataset_name: Bird
  ambrosia_dataset_name: ambrosia

preprocessing:
  used_coref: false
  use_dependency: false
  opensearch: true

test:
  do_run_test: false
